import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import BottomNavigation from "./BottomNavigation";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  description: "Generated by create next app",
  icons: [{rel: 'icon', url: './favicon/favicon-16x16.png'}]

};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>A NEW TITLE</title>

        </Head>

      <body className={inter.className}>
        <main>{children}</main>
        <BottomNavigation />
        <script
          src="https://kit.fontawesome.com/333a269518.js"
          crossOrigin="anonymous"
        ></script>
      </body>
    </html>
  );
}
